##Numpy Array Operations:
1. Create a 1D NumPy Array:
Create a 1D NumPy array named temperatures_w1 for Week 1 with the
following values:
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

In [21]:
import numpy as np

In [22]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

2. Inspection and Properties:

● Inspect the shape, data type, and the number of elements in the array.
Inspect the shape of the temperatures_w1 array.

In [23]:
print(temperatures_w1.shape)

(7,)

In [24]:
print(temperatures_w1.dtype)
print(temperatures_w1.size)

float64
7

3. Array Operations:

● Convert the temperatures_w1 from Celsius to Fahrenheit using the
formula: Fahrenheit = (Celsius * 9/5) + 32
● Find the maximum, minimum, and mean temperatures for the week.

In [25]:
fahrenheit = (temperatures_w1 * 9/5) + 32
print(fahrenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [26]:
print("Maximum temperature:", np.max(temperatures_w1))
print("Minimum temperature:", np.min(temperatures_w1))
print("Mean temperature:", np.mean(temperatures_w1))

Maximum temperature: 26.1
Minimum temperature: 20.8
Mean temperature: 23.542857142857144

4. Array Slicing and Indexing:

● Extract the temperatures for the first three days of the week.

● Extract the temperatures for the weekend (last two days).

● Extract the temperatures for the middle three days of the week.

In [27]:
# First three days
print("First three days:", temperatures_w1[0:3])

# Weekend - last two days
print("last two days:", temperatures_w1[-2:])

# Middle three days
print("Middle three days:", temperatures_w1[2:5])

First three days: [22.5 25.3 20.8]
last two days: [24.8 21.9]
Middle three days: [20.8 23.4 26.1]

5. Create a 2D Array:

Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:

★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)

★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

In [28]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

6. Inspect and Slice the 2D Array:

● Inspect and print the shape, data type, and total number of elements in the temperatures array.

● Extract the temperatures for each week and the weekends (last two days) for both weeks.

In [29]:
print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Total number of elements:", temperatures.size)

Shape: (2, 7)
Data type: float64
Total number of elements: 14

In [30]:
print("Week 1:", temperatures[0])
print("Week 2:", temperatures[1])

print("Week 1 weekend:", temperatures[0, -2:])
print("Week 2 weekend:", temperatures[1, -2:])

Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Week 1 weekend: [24.8 21.9]
Week 2 weekend: [22.8 20.1]

Pandas Series:

1. Creating Pandas Series:

● Create a Pandas Series named marks with the following data:

➢ Marks: 95, 92, 89, 85, 80

➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [31]:
import pandas as pd

In [32]:
marks = pd.Series([95, 92, 89, 85, 80],index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

2. Indexing and Slicing:

● Use the integer index position to access the mark of the 1st rank student.

● Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels.

● Use the iloc accessor to retrieve the mark of the 3rd rank student.

● Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90.

In [35]:
print(marks.iloc[0])

print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

print(marks.iloc[2])

print(marks[marks > 90])

95
Rank1    95
Rank2    92
Rank3    89
dtype: int64
89
Rank1    95
Rank2    92
dtype: int64

3. Manipulating Series:

● Modify the mark of the student with the 1st rank to 100.

● Remove the entry corresponding to the last rank from the Series.

● Compute the CGPA by dividing each mark in the Series by 10.

In [36]:
marks['Rank1'] = 100
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [37]:
marks = marks.drop('Rank5')
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [38]:
cgpa = marks / 10
print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

Pandas DataFrame:

1. Creating Pandas DataFrame:

● Create a Pandas DataFrame named transactions with the following data:

➢ TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110

➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture','Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West','South', 'North'

➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [39]:
transactions = {
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "ProductCategory": ['Electronics', 'Clothing', 'Electronics', 'Furniture',
                        'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Furniture', 'Electronics'],
    "Region": ['North', 'South', 'North', 'East', 'West',
               'North', 'East', 'West', 'South', 'North'],
    "Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}

transactions=pd.DataFrame(transactions)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

2. Data Exploration:
● Display the transactions DataFrame and its basic information, including
head, tail, shape, column names, and data types.

In [48]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [42]:
#Head
transactions.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [44]:
#Tail
transactions.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [45]:
#shape
transactions.shape

(10, 4)

In [46]:
#column names
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

In [47]:
#Data type
transactions.dtypes

TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

● Display only the 'ProductCategory' and 'Amount' columns.

In [49]:
print(transactions[['ProductCategory', 'Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [50]:
print(transactions.iloc[:, 1:4])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

In [51]:
print(transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)])

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

● Find the value counts for the 'ProductCategory' column.

In [52]:
print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

● Find the unique values in the 'Region' column.

In [53]:
print(transactions['Region'].unique())

<StringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

● Group by 'Region' and find the mean amount for each region.

In [54]:
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

3. Manipulating the DataFrame:
● Modify the 'Amount' for the transaction with TransactionID 102 to 165.

In [55]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

● Add a new column 'Discount' by calculating 10% of the 'Amount'

In [56]:
transactions['Discount'] = transactions['Amount'] * 0.10

● Remove the row with TransactionID 109.

In [59]:
transactions.drop(8, axis=0, inplace=True)

KeyError: '[8] not found in axis'

● Delete the 'Discount' column from the DataFrame.

In [61]:
transactions.drop("Discount", axis=1, inplace=True)